version: '2'

#networks:
#  frontend:
#    ipam:
#      config:
#        - subnet: 172.30.0.0/24

services:
  bind:
    restart: always
    image: suculent/bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - ./data:/data
    environment:
    - ROOT_PASSWORD=secretpassword
#    networks:
#        frontend:
#            ipv4_address: 172.30.0.112
